["protostar.config"]
protostar_version = "0.2.5"

["protostar.project"]
libs_path = "lib"

["protostar.shared_command_configs"]
cairo_path = ["src", "lib/cairo_contracts/src"]

["protostar.contracts"]
timestamp_based_account = [
    "src/onlydust/accounts/timestamp_based_account/account.cairo",
]
